services:
  - type: web
    name: scoring-api
    env: python
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main_api_fastapi_secured:app --host 0.0.0.0 --port 10000
